_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.1
            "6": 4.47.0
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
beta:
    value: 0.5
lambda_gkd:
    value: 0.5
optimizer:
    value:
        betas:
            - 0.9
            - 0.999
        lr: 5e-05
        weight_decay: 0.01
temperature:
    value: 1
